name: Auto Deploy Wallpaper Gallery
on:
  push:
    branches: [ paper ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sparse Checkout (Only metadata)
        uses: actions/checkout@v4
        with:
          # 关键：只获取最近一次提交，且不下载 LFS 文件
          fetch-depth: 1
          filter: blob:none 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Index
        run: |
          # 只列出文件结构，不下载内容
          git ls-tree -r paper --name-only > files.txt
          python .github/py/update_nav.py files.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
