name: Auto Deploy Wallpaper Gallery
on:
  push:
    branches:
      - paper  # 监听你的主要图片分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Navigation Page
        run: python .github/py/update_nav.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # 页面文件会被推送到这个自动生成的分支
